name: Bug report
description: Create a report to help us improve.
title: "Bug Report: "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please fill out the form below.
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce_steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste images or drag-and-drop them here.
    validations:
      required: false
  - type: input
    id: desktop_info
    attributes:
      label: Desktop (please complete the following information)
      description: OS, Browser, and Version (e.g. iOS, Chrome, 22)
    validations:
      required: false
  - type: input
    id: smartphone_info
    attributes:
      label: Smartphone (please complete the following information)
      description: Device, OS, Browser, and Version (e.g. iPhone6, iOS8.1, Safari, 22)
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false