name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

body:
  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.

  - type: textarea
    id: reproduce_steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior:
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: desktop_info
    attributes:
      label: Desktop (please complete the following information)
      description: OS, Browser, and Version details.
      value: |
        - OS: [e.g. iOS]
        - Browser: [e.g. chrome, safari]
        - Version: [e.g. 22]

  - type: input
    id: smartphone_info
    attributes:
      label: Smartphone (please complete the following information)
      description: Device, OS, Browser, and Version details.
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser: [e.g. stock browser, safari]
        - Version: [e.g. 22]

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
